#!/bin/bash

APP_NAME=cpp-run
SRC_PATH=/usr/local/src/$APP_NAME/src
BIN_PATH=/usr/local/src/$APP_NAME/bin
OUTPUT_PATH=~/cpp-workspace

errorAndQuit() {
	# Refactor
	echo "Error: '$APP_NAME help' for information."
	exit
}

timestamp() {
  date +"%T"
}

if [[ "$1" != "create" &&  "$1" != "build" ]];
	then
		errorAndQuit
fi

if [[ "$1" == "build" ]];
	then
		if [[ -z "$3" ]];
			then 
				errorAndQuit
		fi

		PROJECT_NAME=$2

		if [[ "$3" == "." ]];
			then
				NAMESPACE=$2
			else
				NAMESPACE=$3
		fi

		current_time=$(timestamp)

		SRC_PATH=$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE
		output_bin=$OUTPUT_PATH/$PROJECT_NAME/bin
		build_dir=$OUTPUT_PATH/$PROJECT_NAME/build/$NAMESPACE
		include_dir=$OUTPUT_PATH/$PROJECT_NAME/include

		mkdir -p $output_bin/old/
		mv $output_bin/*.* $output_bin/old/ 2> /dev/null

		if [[ -z "$4" ]];
			then
				cd $OUTPUT_PATH/$PROJECT_NAME
				git add .
				git commit -a
		fi

		no_errors="yes"
		built_file="no"

		for f in $SRC_PATH/include/*.h;
		do
			file=${f##*/}
			file_name=${file::-4}
			echo $include_dir/$NAMESPACE/$file
			if ! [[ -e "$include_dir/$NAMESPACE/$file" ]] || [[ "$f" -nt "$include_dir/$NAMESPACE/$file" ]];
				then
					cp $f $include_dir/$NAMESPACE/$file
			fi
		done

		for f in $SRC_PATH/src/*.cpp;
		do
			file=${f##*/}
			file_name=${file::-4}
			if ! [[ -e "$build_dir/$file_name.o" ]] || [[ "$f" -nt "$build_dir/$file_name.o" ]];
				then
					python "$BIN_PATH/update_files.py" "build_inc" $f
					if g++ -c $f -I $include_dir -o $build_dir/$file_name.out;
						then
							echo "Successfully built the $file." #> /dev/null
							built_file="yes"
						else
							no_errors="no"
					fi
			fi
		done

		if [[ "$no_errors" == "yes" ]];
			then
				g++ $build_dir/*.out -o $output_bin/$current_time-$NAMESPACE.out
				clear
				$OUTPUT_PATH/$PROJECT_NAME/bin/$current_time-$NAMESPACE.out # > $output_bin/$NAMESPACE-$current_time.output
			else
				echo "Build failed."
		fi

		if [[ "$built_file" == "yes" ]];
			then
				# Generate documentation
				echo "" > /dev/null
		fi;
		# clear
		# cat $output_bin/*.output
fi

if [[ "$1" == "create" ]];
	then
		# Check to make sure the thing to create has a name.
		if [ -z "$3" ];
			then 
				errorAndQuit
		fi

		if [[ "$2" == "project" ]];
			then
				PROJECT_NAME=$3

				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/bin"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/build/$PROJECT_NAME/"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/doc"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/include"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/include/$PROJECT_NAME"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/lib"
				# Include, sample, scr
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/include"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/src"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/doc"

				cp "$SRC_PATH/default_main.cpp" "$OUTPUT_PATH/$PROJECT_NAME/src/$PROJECT_NAME/src/Main.cpp"

				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE" "$@"

				cd $OUTPUT_PATH/$PROJECT_NAME/
				git init > /dev/null
				echo 'bin/' > .gitignore
				echo 'build/' >> .gitignore
				git add .
				git commit -m "Initial project setup." > /dev/null
		fi;

		if [[ "$2" == "class" ]];
			then
				if [[ -z "$5" ]];
					then 
						errorAndQuit
				fi

				PROJECT_NAME=$3
				NAMESPACE=$4
				CLASS_NAME=$5

				cp "$SRC_PATH/default_class.cpp" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src/$CLASS_NAME.cpp"
				cp "$SRC_PATH/default_header.h" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/include/$CLASS_NAME.h"

				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/" "$@"
				python "$BIN_PATH/update_files.py" "add_class" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src/Main.cpp" "$CLASS_NAME" "$NAMESPACE"

				cd $OUTPUT_PATH/$PROJECT_NAME/
				git add src/$NAMESPACE/src/$CLASS_NAME.cpp
				git add src/$NAMESPACE/include/$CLASS_NAME.h
				git commit -m "Added '$CLASS_NAME' cpp and h to '$NAMESPACE' namespace." > /dev/null
		fi;

		if [[ "$2" == "namespace" ]];
			then
				if [[ -z "$4" ]];
					then 
						errorAndQuit
				fi

				PROJECT_NAME=$3
				NAMESPACE=$4

				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/build/$NAMESPACE/"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/include"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/doc"
				mkdir -p "$OUTPUT_PATH/$PROJECT_NAME/include/$NAMESPACE"

				cp "$SRC_PATH/default_main.cpp" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE/src/Main.cpp"

				python "$BIN_PATH/parse_new_files.py" "$OUTPUT_PATH/$PROJECT_NAME/src/$NAMESPACE" "$@"
		fi;
fi;
